### ISSUE TITLE
Where is test_tp.pt?

### ISSUE THREAD

**Issue by huzijun1996** [trikpachu/A3GC-IP#1]
I want to test, evaluate_a3gc_tp.py、evaluate_tp.py、evaluate_dip.py、evaluate_ggru_tp.py, but they all tell me that they cannot find 'data/dip-imu/test_tp.pt'
May I ask what this file means? Can you provide or tell me how to generate it?
I can't find amass_data in preprocess.py and cannot find paths. smpl_file, ori5, dip_savepath in postprocess_data.py.

**Comment by trikpachu** [comment]
Well, as "data/dip-imu/test_tp.pt" suggests, "test_tp.pt" is in fact data. The Readme states that I can not provide you with the data, as it is not mine. You have to obtain the data from the listed sources. Then just check the Readme, it tells you how to preprocess the data. e.g. test_tp will be genereated by postprocess.py. The only exception from that is "ori5" in postprocess.py, which was a typo I missed.
